"""
Loader for the SYNTHETIC test fixture in ``tests/fixtures/synthetic_ddi/``.

*** THIS IS NOT A DATASET. IT IS A UNIT-TEST FIXTURE. ***

The two CSVs this module reads were generated by a large language model
(Claude) from parametric memory. They contain plausible drug names, SMILES
strings and interaction statements, but:

  * there is NO citable source, NO URL, NO version and NO licence;
  * nothing in them has been verified against DrugBank, DDInter, PubChem or
    any other database;
  * the interaction labels were written with the CYP450 mechanism in mind, so
    they are circular with respect to any CYP-derived feature.

**Computing or publishing any metric from this fixture is prohibited.** Every
number previously produced from it has been annulled - see LIMITATIONS.md.

The fixture is retained for exactly one purpose: exercising pipeline code
paths (parsing, splitting, negative sampling, batching, training loop) in unit
tests without requiring network access or a licensed download. It lives under
``tests/`` and not under ``data/`` so that its status is unambiguous from the
path alone.

Real data enters the project through ``data/raw/``, populated from
Therapeutics Data Commons - see DATA_PROVENANCE.md.

READING THE FILES
-----------------
Both CSVs carry a multi-line ``#`` prohibition header. We count the leading
comment lines and pass ``skiprows``; we deliberately do NOT use pandas'
``comment="#"``, because that strips everything after a ``#`` anywhere on a
line and five SMILES in this fixture contain ``#`` as a triple bond
(selegiline ``C#CCN(C)...``, efavirenz, verapamil, cimetidine, citalopram).
Using ``comment="#"`` would silently truncate those molecules into different
compounds - a corruption that parses cleanly and would be very hard to notice.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import pandas as pd
from rdkit import Chem, RDLogger
from rdkit.Chem import Descriptors, inchi, rdMolDescriptors

# RDKit is chatty about aromaticity perception on stderr; we do our own,
# stricter validation below, so silence the default logger.
RDLogger.DisableLog("rdApp.*")

PROJECT_ROOT = Path(__file__).resolve().parents[3]
FIXTURE_DIR = PROJECT_ROOT / "tests" / "fixtures" / "synthetic_ddi"
DRUGS_CSV = FIXTURE_DIR / "drugs.csv"
PAIRS_CSV = FIXTURE_DIR / "ddi_pairs.csv"

#: Columns that hold ``|``-separated multi-values.
MULTIVALUE_COLUMNS = (
    "cyp_substrate",
    "cyp_inhibitor",
    "cyp_inducer",
    "transporter_substrate",
    "transporter_inhibitor",
    "pd_class",
)

#: Severity ranked from most to least clinically urgent. The ordering is used
#: to build the ordinal target for the severity head in Step 3.
SEVERITY_ORDER = ("minor", "moderate", "major")


class SyntheticFixtureError(ValueError):
    """The fixture files are internally inconsistent - a bug, not bad input."""


@dataclass
class ValidationReport:
    """Outcome of validating the fixture files. Printed by the data report."""

    n_drugs: int
    n_pairs: int
    unparseable: list[str]
    formula_mismatches: list[tuple[str, str, str]]
    duplicate_structures: dict[str, list[str]]
    unknown_names_in_pairs: list[str]
    isolated_drugs: list[str]
    self_loops: list[str]
    duplicate_pairs: list[tuple[str, str]]

    @property
    def ok(self) -> bool:
        return not any(
            [
                self.unparseable,
                self.formula_mismatches,
                self.duplicate_structures,
                self.unknown_names_in_pairs,
                self.self_loops,
                self.duplicate_pairs,
            ]
        )

    def summary(self) -> str:
        lines = [
            f"SYNTHETIC FIXTURE (not data): {self.n_drugs} drugs, {self.n_pairs} interactions",
            f"  structures parsed + formula-verified : "
            f"{self.n_drugs - len(self.unparseable) - len(self.formula_mismatches)}"
            f"/{self.n_drugs}",
        ]
        if self.unparseable:
            lines.append(f"  ERROR unparseable SMILES        : {self.unparseable}")
        if self.formula_mismatches:
            lines.append(f"  ERROR formula mismatches        : {self.formula_mismatches}")
        if self.duplicate_structures:
            lines.append(f"  ERROR duplicate structures      : {self.duplicate_structures}")
        if self.unknown_names_in_pairs:
            lines.append(f"  ERROR unknown drugs in pairs    : {self.unknown_names_in_pairs}")
        if self.self_loops:
            lines.append(f"  ERROR self-interactions         : {self.self_loops}")
        if self.duplicate_pairs:
            lines.append(f"  ERROR duplicate pairs           : {self.duplicate_pairs}")
        if self.isolated_drugs:
            # Not an error: a drug with no known interaction is legitimate and
            # is in fact a useful negative-only node.
            lines.append(f"  note  drugs with no interaction : {len(self.isolated_drugs)}")
        lines.append(f"  status: {'PASS' if self.ok else 'FAIL'}")
        return "\n".join(lines)


def _count_header_lines(path: Path) -> int:
    """Number of leading ``#`` comment lines in a fixture CSV.

    Counting them and using ``skiprows`` is the only safe way to read these
    files: ``comment="#"`` would truncate the five SMILES containing a triple
    bond. See the module docstring.
    """
    n = 0
    with path.open("rt", encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#"):
                n += 1
            else:
                break
    return n


def _read_fixture_csv(path: Path) -> pd.DataFrame:
    """Read a fixture CSV, skipping its prohibition header."""
    if not path.exists():
        raise FileNotFoundError(
            f"Missing synthetic fixture at {path}. This file is a test fixture, "
            f"not data - it is committed to the repository and should be present."
        )
    return pd.read_csv(path, dtype=str, skiprows=_count_header_lines(path)).fillna("")


def _split_multivalue(value: object) -> list[str]:
    """``'CYP3A4|CYP2D6'`` -> ``['CYP3A4', 'CYP2D6']``; blank -> ``[]``."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return []
    text = str(value).strip()
    return [part for part in text.split("|") if part] if text else []


@lru_cache(maxsize=1)
def load_drugs() -> pd.DataFrame:
    """Load the fixture ``drugs.csv``, adding RDKit-derived structural columns.

    Derived columns (computed, never stored - so they cannot go stale):
      ``mol``            RDKit molecule object
      ``inchikey``       canonical structural identifier (the real join key)
      ``canonical_smiles`` RDKit-canonicalised SMILES
      ``mol_weight``     average molecular weight in Da
      ``formula``        computed formula, compared against ``formula_expected``
    """
    df = _read_fixture_csv(DRUGS_CSV)
    df["mol"] = df["smiles"].map(Chem.MolFromSmiles)

    parsed = df["mol"].notna()
    df["canonical_smiles"] = [
        Chem.MolToSmiles(m) if m is not None else "" for m in df["mol"]
    ]
    df["inchikey"] = [inchi.MolToInchiKey(m) if m is not None else "" for m in df["mol"]]
    df["formula"] = [
        rdMolDescriptors.CalcMolFormula(m) if m is not None else "" for m in df["mol"]
    ]
    df["mol_weight"] = [
        round(Descriptors.MolWt(m), 2) if m is not None else float("nan") for m in df["mol"]
    ]
    df["n_heavy_atoms"] = [m.GetNumHeavyAtoms() if m is not None else 0 for m in df["mol"]]

    for col in MULTIVALUE_COLUMNS:
        df[col + "_list"] = df[col].map(_split_multivalue)

    if not parsed.all():
        bad = df.loc[~parsed, "name"].tolist()
        raise SyntheticFixtureError(f"Unparseable SMILES in fixture drug table: {bad}")

    return df


@lru_cache(maxsize=1)
def load_pairs() -> pd.DataFrame:
    """Load the fixture ``ddi_pairs.csv`` with a canonical, order-independent pair key.

    A drug interaction is symmetric: (warfarin, aspirin) and (aspirin,
    warfarin) are the same fact.  Storing an unordered key as a sorted tuple
    means "have I already seen this pair?" is a set lookup and can never be
    fooled by argument order.  Every downstream component - negative sampling,
    splitting, evaluation - relies on this invariant.
    """
    df = _read_fixture_csv(PAIRS_CSV)
    df["pair_key"] = [
        tuple(sorted((a, b))) for a, b in zip(df["drug_a"], df["drug_b"])
    ]
    # Sort the stored columns too, so drug_a is always the lexicographically
    # smaller name. This removes an entire class of "did I order it right?" bug.
    df["drug_a"] = [k[0] for k in df["pair_key"]]
    df["drug_b"] = [k[1] for k in df["pair_key"]]
    df["severity_rank"] = df["severity"].map(
        {s: i for i, s in enumerate(SEVERITY_ORDER)}
    )
    # `is_dangerous` is the primary binary target: DDInter-style "Major".
    df["is_dangerous"] = (df["severity"] == "major").astype(int)
    # Coarse mechanism family, used for stratified reporting in Step 4.
    df["mechanism_family"] = df["mechanism"].str.split("_").str[0]  # 'pk' or 'pd'
    return df


def validate() -> ValidationReport:
    """Full internal-consistency check of the fixture files.

    Run by ``pytest`` and by ``scripts/00_data_report.py``. This is the guard
    that makes the fixture internally consistent: if I fat-finger a SMILES or misspell a
    drug name in the pair table, this fails loudly instead of quietly training
    on a wrong molecule.
    """
    drugs = load_drugs()
    pairs = load_pairs()

    unparseable = drugs.loc[drugs["mol"].isna(), "name"].tolist()
    formula_mismatches = [
        (r["name"], r["formula_expected"], r["formula"])
        for _, r in drugs.iterrows()
        if r["formula"] and r["formula"] != r["formula_expected"]
    ]

    by_key: dict[str, list[str]] = {}
    for _, r in drugs.iterrows():
        if r["inchikey"]:
            by_key.setdefault(r["inchikey"], []).append(r["name"])
    duplicate_structures = {k: v for k, v in by_key.items() if len(v) > 1}

    known = set(drugs["name"])
    used = set(pairs["drug_a"]) | set(pairs["drug_b"])
    unknown = sorted(used - known)
    isolated = sorted(known - used)
    self_loops = pairs.loc[pairs["drug_a"] == pairs["drug_b"], "drug_a"].tolist()

    seen: set[tuple[str, str]] = set()
    duplicate_pairs = []
    for key in pairs["pair_key"]:
        if key in seen:
            duplicate_pairs.append(key)
        seen.add(key)

    return ValidationReport(
        n_drugs=len(drugs),
        n_pairs=len(pairs),
        unparseable=unparseable,
        formula_mismatches=formula_mismatches,
        duplicate_structures=duplicate_structures,
        unknown_names_in_pairs=unknown,
        isolated_drugs=isolated,
        self_loops=self_loops,
        duplicate_pairs=duplicate_pairs,
    )


def cyp_vocabulary() -> list[str]:
    """Every CYP enzyme mentioned anywhere in the fixture, sorted.

    Used to build the fixed-width CYP indicator vectors in Step 2 and to define
    the metabolic-pathway edges of the interaction graph.
    """
    drugs = load_drugs()
    seen: set[str] = set()
    for col in ("cyp_substrate_list", "cyp_inhibitor_list", "cyp_inducer_list"):
        for values in drugs[col]:
            seen.update(values)
    return sorted(seen)


def transporter_vocabulary() -> list[str]:
    drugs = load_drugs()
    seen: set[str] = set()
    for col in ("transporter_substrate_list", "transporter_inhibitor_list"):
        for values in drugs[col]:
            seen.update(values)
    return sorted(seen)


def pd_class_vocabulary() -> list[str]:
    drugs = load_drugs()
    seen: set[str] = set()
    for values in drugs["pd_class_list"]:
        seen.update(values)
    return sorted(seen)
