// Typed access to the frozen scientific data. The JSON is generated by
// tools/build_frozen_data.py from the frozen git tag; this module only adds
// types and never mutates values.
import raw from "./frozen.json";

export interface ModelRow {
  label: string;
  category: string;
  pooled_mean: number;
  pooled_std: number;
  s3_mean: number | null;
  s3_std: number | null;
  n_seeds: number;
  source: string;
}

export interface Hypothesis {
  id: string;
  status: "confirmatory" | "exploratory";
  comparison: string;
  view: string;
  delta: number;
  ci_low: number;
  ci_high: number;
  t: number;
  raw_p: number;
  holm_p: number;
  dz: number;
  conclusion: string;
}

export interface CalibrationRow {
  seed: number;
  temperature: number;
  ece_raw: number;
  ece_scaled: number;
  brier_raw: number;
  brier_scaled: number;
  auprc_raw: number;
  auprc_scaled: number;
}

export interface FrozenData {
  meta: { frozen_tag: string; frozen_commit: string; provenance_commit: string; generated_note: string };
  dataset: {
    n_drugs: number; n_pairs: number; excluded_drug: string; excluded_pairs: number;
    dataset_version: string; interaction_types: number; sources: string[]; source: string;
  };
  coverage: Record<string, number | string>;
  splits: {
    train_drugs: number; val_drugs: number; test_drugs: number;
    pooled_pairs: number; s3_pairs: number; prevalence: number; source: string;
  };
  leakage: { both_endpoints_seen: Record<string, number>; note: string; source: string };
  models: ModelRow[];
  ladder: ModelRow[];
  hypotheses: Hypothesis[];
  calibration: CalibrationRow[];
  interpretability: { molecular: number; protein: number; pathway: number; n_pairs: number; source: string; note: string };
  control_e: { r2_train: number; held_out_target_variance: number; identifiable: boolean; note: string; source: string };
  control_f: { changed_fraction: number; retained_fraction: number; note: string; source: string };
  scaffold_disjoint: { evaluated: boolean; note: string };
  config: Record<string, number | string>;
  checkpoint: { seed0_run_id: string; seed0_sha256: string; installed: boolean; note: string };
}

export const frozen = raw as unknown as FrozenData;

export function model(label: string): ModelRow {
  const m = frozen.models.find((x) => x.label === label) ?? frozen.ladder.find((x) => x.label === label);
  if (!m) throw new Error(`model not found in frozen data: ${label}`);
  return m;
}

export function hypothesis(id: string): Hypothesis {
  const h = frozen.hypotheses.find((x) => x.id === id);
  if (!h) throw new Error(`hypothesis not found: ${id}`);
  return h;
}
