#!/usr/bin/env python3
"""
Run all three splitting schemes on the real data and tabulate what each does.

    python scripts/09_split_comparison.py
    python scripts/09_split_comparison.py --seeds 0 1 2

Writes reports/split_comparison.csv and reports/split_comparison.md.

This is the foundation of the Phase A headline artefact. It does not train
anything - it establishes what each scheme actually produces, so that a later
drop in metrics can be attributed to a known, measured change in the evaluation
setup rather than to something unexamined.

The number to look at is `test_S1_fraction`: the share of test pairs whose two
endpoints both appeared in a training pair. Those are the pairs a model can
score from memorised node identity without representing the interaction at all.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd

from ddinet.data import leakage, split as split_mod, tdc_drugbank as tdc

REPORTS = Path(__file__).resolve().parents[1] / "reports"
SCHEMES = ("random_pair", "drug", "scaffold")


def _markdown_table(df: pd.DataFrame) -> str:
    """Render a DataFrame as a markdown table.

    Hand-rolled rather than pandas' to_markdown, which needs the `tabulate`
    package. Adding a dependency for one cosmetic call would mean every future
    reproduction of this project has to install it too.
    """
    cols = [str(c) for c in df.columns]
    head = "| " + " | ".join(cols) + " |"
    rule = "|" + "|".join("---" for _ in cols) + "|"
    body = [
        "| " + " | ".join(f"{v}" for v in row) + " |"
        for row in df.itertuples(index=False)
    ]
    return "\n".join([head, rule, *body])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--seeds", type=int, nargs="+", default=[0])
    ap.add_argument("--val-fraction", type=float, default=0.15)
    ap.add_argument("--test-fraction", type=float, default=0.15)
    args = ap.parse_args()

    pd.set_option("display.width", 240)

    drugs = tdc.load_drugs()
    pairs = tdc.load_pairs()
    print(f"Loaded {len(drugs):,} drugs and {len(pairs):,} unordered pairs\n")

    reports: list[leakage.LeakageReport] = []
    rows: list[dict] = []

    for seed in args.seeds:
        for scheme in SCHEMES:
            print(f"--- scheme={scheme} seed={seed} ---")
            sp = split_mod.build_any(
                scheme, drugs, pairs,
                val_fraction=args.val_fraction,
                test_fraction=args.test_fraction,
                seed=seed,
            )
            # Strict schemes raise here if they leak. Measured schemes report.
            rep = leakage.verify(sp)
            print(rep.summary())
            print()
            reports.append(rep)
            row = leakage.compare_schemes([rep]).iloc[0].to_dict()
            row["seed"] = seed
            rows.append(row)

    table = pd.DataFrame(rows)
    cols = ["scheme", "seed"] + [c for c in table.columns if c not in ("scheme", "seed")]
    table = table[cols]

    print("=" * 110)
    print("SPLIT COMPARISON")
    print("=" * 110)
    print(table.to_string(index=False))

    REPORTS.mkdir(parents=True, exist_ok=True)
    table.to_csv(REPORTS / "split_comparison.csv", index=False)

    md: list[str] = []
    w = md.append
    w("# Split scheme comparison - TDC DrugBank\n")
    w("Generated by `scripts/09_split_comparison.py`. No model is trained here; "
      "this establishes what each evaluation setup actually produces.\n")
    w(f"Source: {len(drugs):,} drugs, {len(pairs):,} unordered pairs, "
      f"val={args.val_fraction:.0%} test={args.test_fraction:.0%}, "
      f"seeds={args.seeds}.\n")
    w("## The table\n")
    w(_markdown_table(table))
    w("")
    w("## How to read it\n")
    w("**`test_S1_fraction`** is the headline. It is the share of test pairs "
      "whose two endpoints *both* appeared in a training pair - the pairs a "
      "model can score from memorised node identity without representing the "
      "interaction mechanism at all.\n")
    w("**`drug_overlap_train_test`** is the count of molecules present on both "
      "sides. For `drug` and `scaffold` this is a hard invariant: the verifier "
      "raises `LeakageError` and aborts the run if it is not zero. For "
      "`random_pair` it is expected, and reported rather than rejected - the "
      "scheme exists to be measured, not used.\n")
    w("**`discarded_pairs`** is nonzero only for the strict schemes. They throw "
      "away pairs straddling the validation and test drug groups, because "
      "otherwise a drug tuned on during validation reappears at test time. "
      "The leaky scheme has no drug groups to straddle and so discards nothing - "
      "part of its apparent advantage is simply that it trains on more data, and "
      "that should be stated when comparing.\n")
    w("## What this does not show\n")
    w("Nothing here is a performance number. A scheme that leaks does not "
      "necessarily produce a higher AUPRC - that is the hypothesis Phase A "
      "tests, and it has to be tested by training models on these splits. This "
      "table establishes only that the schemes differ in the way they are "
      "supposed to differ, and by how much.\n")
    (REPORTS / "split_comparison.md").write_text("\n".join(md))
    print(f"\nWrote {REPORTS/'split_comparison.csv'} and "
          f"{REPORTS/'split_comparison.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
